sudo: required
dist: trusty
language: python
python:
  - "2.7"
  #- "3.4" # Note that hyperopt currently seems to have issues with 3.4
install:
  # code below is taken from http://conda.pydata.org/docs/travis.html
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - travis_retry conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION nose
  - source activate test-environment
  - pip install Cython --install-option="--no-cython-compile"
  - pip install -e .[tests]
script:
  - python -c "import keras.backend"
  - py.test tests/
after_success:
  - coveralls
